Q1. Write a Python Program to Add Two Matrices?

In [1]:
#solution 1
mat1 = [[1,6,4],
        [4,5,6],
        [7,6,9]]

mat2 = [[2,5,4],
        [5,8,7],
        [8,3,1]]

sumMat = [[0,0,0],
          [0,0,0],
          [0,0,0]]

sumMat = [[mat1[i][j] + mat2[i][j] for j in range(len(mat1[0]))] for i in range(len(mat1))]
print("The Sum of two matrix {}  and {}  is \n{} ".format(mat1,mat2,sumMat))

The Sum of two matrix [[1, 6, 4], [4, 5, 6], [7, 6, 9]]  and [[2, 5, 4], [5, 8, 7], [8, 3, 1]]  is 
[[3, 11, 8], [9, 13, 13], [15, 9, 10]] 


In [2]:
# solution 2
import numpy as np

mat1 = np.array([[1,6,4],
        [4,5,6],
        [7,6,9]])
mat2 = np.array([[2,5,4],
        [5,8,7],
        [8,3,1]])

sumMat = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,sumMat))

The Sum of two matrix 

[[1 6 4]
 [4 5 6]
 [7 6 9]]  and 

[[2 5 4]
 [5 8 7]
 [8 3 1]]  is 

[[ 3 11  8]
 [ 9 13 13]
 [15  9 10]] 


Q2. Write a Python Program to Multiply Two Matrices?

In [3]:
## Solution 1
# Program to multiply two matrices

def initializeMatrix(n,v=0):
    M=[]             
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(v)
        M.append(row)
    return(M)

def createMatrix(n):
    
    M=[]             
    print("Enter the element :")
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(int(input()))
        M.append(row)
    return(M)

def printMatrix(M,n):
    for i in range(n):
        for j in range(n):
            print(M[i][j], end=" ")
        print() 
def mulMatrix(A,B,result):        
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] = result[i][j] + A[i][k] * B[k][j]
    return result
    
        
n=int(input("Enter N for N x N matrix: "))       
M1 = createMatrix(n)

#Display the 2D array
print("Display Array M1 In Matrix Form")
printMatrix(M1,n)


M2 = createMatrix(n)

#Display the 2D array
print("Display Array M2 In Matrix Form")
printMatrix(M2,n)


sumMat = initializeMatrix(n)

for i in range(len(M1)):
    for j in range(len(M1[0])):
        sumMat[i][j] = M1[i][j] + M2[i][j]
        
print("Result Matrix")
for r in sumMat:
    print(r)

Enter N for N x N matrix: 2
Enter the element :
1
2
3
4
Display Array M1 In Matrix Form
1 2 
3 4 
Enter the element :
3
4
5
6
Display Array M2 In Matrix Form
3 4 
5 6 
Result Matrix
[4, 6]
[8, 10]


In [4]:
# solution 2
import numpy as np

mat1 = np.array([[1,2,4],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[2,3,4],
        [5,6,7],
        [8,9,1]])

sumMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,sumMat))

The product of two matrix 

[[1 2 4]
 [4 5 6]
 [7 8 9]]  and 

[[2 3 4]
 [5 6 7]
 [8 9 1]]  is 

[[ 44  51  22]
 [ 81  96  57]
 [126 150  93]] 


In [5]:
# Program to multiply two matrices

def initializeMatrix(n,v=0):
    M=[]             
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(v)
        M.append(row)
    return(M)

def createMatrix(n):
    
    M=[]             
    print("Enter the element :")
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(int(input()))
        M.append(row)
    return(M)

def printMatrix(M,n):
    for i in range(n):
        for j in range(n):
            print(M[i][j], end=" ")
        print() 
def mulMatrix(A,B,result):        
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] = result[i][j] + A[i][k] * B[k][j]
    return result
    
        
n=int(input("Enter N for N x N matrix: "))       
M1 = createMatrix(n)

#Display the 2D array
print("Display Array M1 In Matrix Form")
printMatrix(M1,n)


M2 = createMatrix(n)

#Display the 2D array
print("Display Array M2 In Matrix Form")
printMatrix(M2,n)


result = initializeMatrix(n)


result = mulMatrix(M1,M2,result)
print("Result Matrix")
for r in result:
    print(r)

Enter N for N x N matrix: 2
Enter the element :
4
5
6
6
Display Array M1 In Matrix Form
4 5 
6 6 
Enter the element :
2
3
4
5
Display Array M2 In Matrix Form
2 3 
4 5 
Result Matrix
[28, 37]
[36, 48]


Q3. Write a Python Program to Transpose a Matrix?

In [6]:
def initializeMatrix(n,v=0):
    M=[]             
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(v)
        M.append(row)
    return(M)

def createMatrix(n):
    
    M=[]             
    print("Enter the element :")
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(int(input()))
        M.append(row)
    return(M)

def printMatrix(M,n):
    for i in range(n):
        for j in range(n):
            print(M[i][j], end=" ")
        print() 
        
def transposeMatrix(M,n,result):
    for i in range(n):
        for j in range(n):
            result[i][j]= M[j][i]
    return result

n=int(input("Enter N for N x N matrix: "))       
M1 = createMatrix(n)
#Display the 2D array
print("Display Array M1 In Matrix Form")
printMatrix(M1,n)

result = initializeMatrix(n)
result = transposeMatrix(M1,n,result)
print("Transposed Matrix")
for r in result:
    print(r)

Enter N for N x N matrix: 2
Enter the element :
3
4
5
6
Display Array M1 In Matrix Form
3 4 
5 6 
Transposed Matrix
[3, 5]
[4, 6]


Q4. Write a Python Program to Sort Words in Alphabetic Order?

In [8]:
str = input("Enter some string: ")

words = str.split()
words.sort()
for word in words:
    print(word)

Enter some string: My name is Rajeshwari
My
Rajeshwari
is
name


Q5. Write a Python Program to Remove Punctuation From a String?

In [9]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

str = input("Enter some string with panctuations")

# remove punctuation from the string
no_punct = ""
for char in str:
    if char not in punctuations:
        no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)

Enter some string with panctuations" The dish was amazin! "
 The dish was amazin 
